### ISSUE TITLE
Add README.dev.md file

### ISSUE THREAD

**Issue by abelsiqueira** [TNO-Tulipa/TulipaBulb.jl#1] opened 2023-08-09 18:26 UTC
This file should describe how to setup the environment to develop the package. For instance, installing pre-commit.
Check https://github.com/abelsiqueira/PlaygroundWithGit.jl for example.

**Comment by clizbe** [comment] 2023-08-11 14:24
Is this not a duplicate of #5?

**Comment by clizbe** [comment] 2023-08-11 15:24
Oh nvm I didn't realize GIT numbers both Issues and Pull Requests.

**Closed** 2023-08-16 14:01 UTC
Labels: Zone: documentation, Type: addition
